version: '3.7'

services:

  postgres:
    image: postgres:12
    ports:
      - 54322:5432
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - transaction-summary-net

  transaction-summary:
    image: vijaykdotcom/transaction-summary:latest
    depends_on:
      - postgres
    environment:
      - dbHost=postgres
      - kafkaHost=kafka
      - kafkaPort=29092
    volumes:
      - "./logs:/logs"
    ports:
      - 8080:8080
    networks:
      - transaction-summary-net
      - external-kafka-net

networks:
  transaction-summary-net:
    name: transaction-summary-net
    driver: bridge
  external-kafka-net:
    external: true
    name: kafka-net
